[workspace]
members = [
  "crates/common",
  "crates/kernel",
  "crates/init",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
bitflags = "2.6"

[profile.release]
panic = "abort"
